#!/usr/bin/env python3
"""
gen_cmd_registry.py  —  从 CMD_DEFINE / CMD_RESERVE 宏声明自动生成命令注册文件

扫描 --src-dir 下所有 .h 文件中的 CMD_DEFINE / CMD_RESERVE 宏，
生成以下文件到 --out-dir：
  1. CmdRegistry_gen.h   — CmdId 枚举 + 参数索引枚举 + cmdIdToName()
  2. CmdHead_gen.h       — 所有已实现命令的 #include
  3. CmdNameToId_gen.h   — name → CmdId 映射 (NRT 侧)
  4. message_gen.proto    — 每个带参数的命令生成 protobuf message

用法:
  python3 tool/gen_cmd_registry.py \
      --src-dir zrcs_rt/command \
      --out-dir build/generated
"""

import argparse
import os
import re
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# 正则：匹配 CMD_DEFINE(...) 和 CMD_RESERVE(...)，支持跨行
# ---------------------------------------------------------------------------
_MACRO_RE = re.compile(
    r'\b(CMD_DEFINE|CMD_RESERVE)\s*\(\s*'
    r'(\w+)\s*,\s*'           # className
    r'(\d+)\s*'               # cmdId
    r'(?:,\s*((?:PARAM\s*\(\s*\w+\s*\)\s*)*))?'  # 可选的 PARAM(...) 列表
    r'\)',
    re.DOTALL
)

_PARAM_RE = re.compile(r'PARAM\s*\(\s*(\w+)\s*\)')


def _parse_params(raw: str | None) -> list[str]:
    """从 'PARAM(X) PARAM(Y) ...' 字符串中提取参数名列表。"""
    if not raw:
        return []
    return _PARAM_RE.findall(raw)


# ---------------------------------------------------------------------------
# 扫描
# ---------------------------------------------------------------------------
class CmdEntry:
    __slots__ = ('name', 'cmd_id', 'params', 'implemented', 'source_file')

    def __init__(self, name: str, cmd_id: int, params: list[str],
                 implemented: bool, source_file: str):
        self.name = name
        self.cmd_id = cmd_id
        self.params = params
        self.implemented = implemented
        self.source_file = source_file


def scan_directory(src_dir: str) -> list[CmdEntry]:
    entries: list[CmdEntry] = []
    src_path = Path(src_dir)

    for hfile in sorted(src_path.glob('*.h')):
        content = hfile.read_text(encoding='utf-8', errors='replace')
        for m in _MACRO_RE.finditer(content):
            macro_type = m.group(1)  # CMD_DEFINE or CMD_RESERVE
            class_name = m.group(2)
            cmd_id = int(m.group(3))
            params = _parse_params(m.group(4))
            implemented = (macro_type == 'CMD_DEFINE')
            entries.append(CmdEntry(class_name, cmd_id, params,
                                    implemented, hfile.name))
    return entries


def validate(entries: list[CmdEntry]) -> None:
    ids_seen: dict[int, str] = {}
    names_seen: dict[str, int] = {}
    errors: list[str] = []

    for e in entries:
        if e.cmd_id <= 0:
            errors.append(f'{e.name}: CmdId 必须 > 0 (got {e.cmd_id})')
        if e.cmd_id in ids_seen:
            errors.append(
                f'CmdId {e.cmd_id} 重复: {ids_seen[e.cmd_id]} 和 {e.name}')
        ids_seen[e.cmd_id] = e.name
        if e.name in names_seen:
            errors.append(
                f'命令名 {e.name} 重复: id {names_seen[e.name]} 和 {e.cmd_id}')
        names_seen[e.name] = e.cmd_id

    if errors:
        for err in errors:
            print(f'ERROR: {err}', file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# 生成
# ---------------------------------------------------------------------------
_HEADER = '// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY\n// Generated by tool/gen_cmd_registry.py\n'


def gen_cmd_registry(entries: list[CmdEntry]) -> str:
    """生成 CmdRegistry_gen.h。"""
    sorted_entries = sorted(entries, key=lambda e: e.cmd_id)
    sentinel = max(e.cmd_id for e in entries) + 1 if entries else 1

    lines = [_HEADER, '#pragma once\n',
             '#include <cstdint>\n',
             '#include "shared_memory/ShmLayout.h"\n',
             '']

    # ── CmdId enum ──
    lines.append('enum class CmdId : uint16_t {')
    lines.append('    INVALID      = 0,')
    for e in sorted_entries:
        lines.append(f'    {e.name:<12s} = {e.cmd_id},')
    lines.append(f'    SENTINEL     = {sentinel}')
    lines.append('};\n')

    # ── 参数索引枚举 ──
    for e in sorted_entries:
        if e.params:
            members = ', '.join(f'{e.name}{p}' for p in e.params)
            lines.append(f'enum {{ {members} }};')
    lines.append('')

    # ── AXISMAXCOUNT ──
    lines.append('inline constexpr size_t AXISMAXCOUNT = zrcs::kAxisMax;\n')

    # ── cmdIdToName ──
    lines.append('namespace zrcs {\n')
    lines.append('inline const char* cmdIdToName(uint16_t id) noexcept {')
    lines.append('    static constexpr const char* kTable[] = {')

    # 填充稀疏表，gap 位置用 "UNKNOWN"
    max_id = max(e.cmd_id for e in entries) if entries else 0
    id_map = {e.cmd_id: e.name for e in entries}
    for i in range(max_id + 1):
        name = id_map.get(i, 'UNKNOWN') if i > 0 else 'INVALID'
        lines.append(f'        "{name}",{" " * max(1, 16 - len(name))}// {i}')
    lines.append('    };')
    lines.append('    constexpr size_t kTableSize = sizeof(kTable) / sizeof(kTable[0]);')
    lines.append('    if (id < kTableSize) return kTable[id];')
    lines.append('    return "UNKNOWN";')
    lines.append('}')
    lines.append('\n} // namespace zrcs\n')

    return '\n'.join(lines)


def gen_cmd_head(entries: list[CmdEntry]) -> str:
    """生成 CmdHead_gen.h — 只包含已实现的命令。"""
    impl = sorted([e for e in entries if e.implemented], key=lambda e: e.name)
    lines = [_HEADER, '#pragma once\n']
    for e in impl:
        # 使用实际文件名而非类名，避免大小写不匹配
        lines.append(f'#include "command/{e.source_file}"')
    lines.append('')
    return '\n'.join(lines)


def gen_cmd_name_to_id(entries: list[CmdEntry]) -> str:
    """生成 CmdNameToId_gen.h。"""
    sorted_entries = sorted(entries, key=lambda e: e.cmd_id)
    lines = [_HEADER, '#pragma once\n',
             '#include <string>',
             '#include <unordered_map>',
             '#include "CmdRegistry_gen.h"\n',
             'namespace zrcs {\n',
             'inline const std::unordered_map<std::string, CmdId>& cmdNameToId() {',
             '    static const std::unordered_map<std::string, CmdId> kMap = {']
    for e in sorted_entries:
        lines.append(f'        {{"{e.name}",{" " * max(1, 14 - len(e.name))}CmdId::{e.name}}},')
    lines.append('    };')
    lines.append('    return kMap;')
    lines.append('}')
    lines.append('\n} // namespace zrcs\n')
    return '\n'.join(lines)


def _to_snake(name: str) -> str:
    """CamelCase → snake_case，用于 proto 字段名。"""
    s = re.sub(r'([A-Z])', r'_\1', name).lower().lstrip('_')
    return s


def gen_message_proto(entries: list[CmdEntry]) -> str:
    """生成 message_gen.proto — 带参数的命令生成 protobuf message。"""
    lines = [
        '// AUTO-GENERATED FILE — DO NOT EDIT MANUALLY',
        '// Generated by tool/gen_cmd_registry.py',
        'syntax = "proto3";',
        '',
        'package zrcs_message;',
        '',
    ]
    sorted_entries = sorted(entries, key=lambda e: e.cmd_id)
    for e in sorted_entries:
        if not e.params:
            continue
        lines.append(f'message {e.name}Command {{')
        for idx, p in enumerate(e.params, start=1):
            lines.append(f'    double {_to_snake(p)} = {idx};')
        lines.append('}')
        lines.append('')
    return '\n'.join(lines)


# ---------------------------------------------------------------------------
# 写入（仅在内容变化时才写，避免不必要的重编译）
# ---------------------------------------------------------------------------
def write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        existing = path.read_text(encoding='utf-8', errors='replace')
        if existing == content:
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')
    return True


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description='Generate command registry files')
    parser.add_argument('--src-dir', required=True,
                        help='Directory containing command .h files')
    parser.add_argument('--out-dir', required=True,
                        help='Output directory for generated files')
    args = parser.parse_args()

    entries = scan_directory(args.src_dir)
    if not entries:
        print('WARNING: No CMD_DEFINE/CMD_RESERVE found, generating empty stubs',
              file=sys.stderr)

    validate(entries)

    out = Path(args.out_dir)
    changed = 0
    changed += write_if_changed(out / 'CmdRegistry_gen.h', gen_cmd_registry(entries))
    changed += write_if_changed(out / 'CmdHead_gen.h', gen_cmd_head(entries))
    changed += write_if_changed(out / 'CmdNameToId_gen.h', gen_cmd_name_to_id(entries))
    changed += write_if_changed(out / 'message_gen.proto', gen_message_proto(entries))

    print(f'gen_cmd_registry: {len(entries)} commands, {changed} file(s) updated')


if __name__ == '__main__':
    main()
